In [1]:
import pandas as pd
import pickle
import torch

/Users/kotzen/opt/anaconda3/envs/pyro/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
inf = pd.read_csv('../results/infectivity/2024-01-16/mutation_effects.csv')
neup = pd.read_csv('../results/neutralization/2023-12-20/mutation_effects_within_pools.csv')
neu = pd.read_csv('../results/neutralization/2023-12-20/mutation_effects_across_pools.csv')

In [4]:
with open('../model_infectivity/2024-01-16/mcmc_chain.pkl', 'rb') as p:
    inf_samples = pickle.load(p)
with open('../model_neutralization/2023-12-20/mcmc_chain.pkl', 'rb') as p:
    neu_samples = pickle.load(p)

In [11]:
inf_samples['σ_m'].mean()

tensor(0.7791)

In [18]:
inf[inf['Effect'].apply(lambda x: abs(x)) > inf_samples['σ_m'].mean().item()].sort_values(by='Effect', ascending=False)

    Mutation    Effect      N
162    S704L  2.319440   48.0
32     E484V  2.012744   30.0
134    R158A  0.942593    6.0
148    R683V  0.942112    6.0
43     F486V  0.927232  105.0
147    R683N  0.910675   18.0
105    N460K  0.865734  207.0
130    Q498R  0.828982  330.0
183     T95I -0.868979   12.0
167     T19R -0.937455    9.0
131    Q498Y -1.029732   21.0
170    T299I -1.099025    3.0
102    N439R -1.357700   24.0
35     E619Q -1.415712    3.0
152    S155R -1.796388   55.0
143    R403T -2.608914   12.0

In [20]:
inf.sort_values(by='Effect', ascending=False)

    Mutation    Effect      N
162    S704L  2.319440   48.0
32     E484V  2.012744   30.0
134    R158A  0.942593    6.0
148    R683V  0.942112    6.0
43     F486V  0.927232  105.0
..       ...       ...    ...
170    T299I -1.099025    3.0
102    N439R -1.357700   24.0
35     E619Q -1.415712    3.0
152    S155R -1.796388   55.0
143    R403T -2.608914   12.0

[213 rows x 3 columns]